spring:
  datasource:
    url:
      jdbc:h2:mem: javadevjournal
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    spring:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate.dll.auto: create-drop